- build.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/io/kevinlee/pdf2excel/cba/CbaPageHandler.scala
Upgraded: sbt `1.2.8` => `1.3.3` / sbt-wartremover `2.2.1` => `2.4.3`
> Upgraded: sbt 1.2.8 => 1.3.3 / sbt-wartremover 2.2.1 => 2.4.3

- project/build.properties
> Upgraded: sbt 1.3.6 => 1.3.7

- build.sbt
> Upgraded: libraries

- src/main/scala/io/kevinlee/pdf2excel/Pdf2Excel.scala
- src/main/scala/io/kevinlee/pdf2excel/cba/CbaPageHandler.scala
- src/main/scala/io/kevinlee/pdf2excel/cba/CbaPageHandler2.scala
- src/main/scala/io/kevinlee/pdf2excel/data.scala
> Clean up and Reformatting

- project/build.properties
- project/plugins.sbt
Upgraded: sbt 1.3.8 => 1.3.10 / wartremover 2.4.3 => 2.4.5
> Upgraded: sbt 1.3.8 => 1.3.10 / wartremover 2.4.3 => 2.4.5

- build.sbt
Upgraded: Scala 2.12.10 => 2.12.11 / 2.13.1 => 2.13.2
> Upgraded: Scala 2.12.10 => 2.12.11 / 2.13.1 => 2.13.2

- build.sbt
- project/plugins.sbt
Upgraded: Scala 2.13.2 => 2.12.12 / sbt-wartremover 2.4.5 => 2.14.10
> Upgraded: Scala 2.13.2 => 2.12.12 / sbt-wartremover 2.4.5 => 2.14.10

- build.sbt
> Added: more libraries

- src/main/scala/io/kevinlee/pdf2excel/Pdf2Excel.scala
- src/main/scala/io/kevinlee/pdf2excel/data.scala
- src/main/scala/io/kevinlee/pdf2excel/ing/IngPageHandler.scala
> Added: Support ING statement

- src/main/scala/io/kevinlee/pdf2excel/ing/IngPageHandler.scala
Fixed: bug in transaction finding logic
> Fixed: bug in transaction finding logic

- project/build.properties
Upgraded: sbt `1.3.10` => `1.4.4`
> Upgraded: sbt 1.3.10 => 1.4.4

- build.sbt
- project/plugins.sbt
Clean up `build.sbt` and upgrade sbt plugin
> Clean up build.sbt and upgrade sbt plugin

- project/build.properties
Upgrade: sbt `1.5.2` => `1.6.2`
> Upgrade: sbt 1.5.2 => 1.6.2

- src/main/scala/io/kevinlee/pdf2excel/ing/IngPageHandler.scala
Add: filtering out internal transaction fee rebate for ING
> Add: filtering out internal transaction fee rebate for ING

- .scalafmt.conf
> Add: .scalafmt.conf

- .git-blame-ignore-revs
- src/main/scala/io/kevinlee/parsers/Parsers.scala
- src/main/scala/io/kevinlee/pdf2excel/Pdf2Excel.scala
- src/main/scala/io/kevinlee/pdf2excel/cba/CbaPageHandler.scala
- src/main/scala/io/kevinlee/pdf2excel/cba/CbaPageHandler2.scala
- src/main/scala/io/kevinlee/pdf2excel/data.scala
- src/main/scala/io/kevinlee/pdf2excel/ing/IngPageHandler.scala
- src/main/scala/io/kevinlee/pdf2excel/nab/NabPageHandler.scala
* Reformat the code
* Add: `.git-blame-ignore-revs`
> Reformat the code

- src/main/scala/io/kevinlee/pdf2excel/Pdf2Excel.scala
Minor change - use FQN for Handler
> Minor change - use FQN for Handler

- build.sbt
Bump cats to `2.9.0` and cats-effect to `2.5.5`
> Bump cats to `2.9.0` and cats-effect to `2.5.5`

- build.sbt
- src/main/scala/io/kevinlee/pdf2excel/Pdf2Excel.scala
- src/main/scala/io/kevinlee/pdf2excel/Pdf2ExcelApp.scala
Partially adopt effectie with cats-effect 2
> Partially adopt effectie with cats-effect 2

- project/build.properties
> Bump sbt to 1.9.3

- build.sbt
- src/main/scala/pdf2excel/Pdf2ExcelApp.scala
Add and bump libraries
- Add `log4j-to-slf4j`
- effectie to `2.0.0-beta12`
- logger-f to `2.0.0-beta20`
- extras to `0.42.0`
- Replace `logger-f-log4s` with `logger-f-slf4j`
> Add and bump libraries

- src/main/scala/pdf2excel/Pdf2Excel.scala
- src/main/scala/pdf2excel/cba/CbaPageHandler.scala
- src/main/scala/pdf2excel/cba/CbaPageHandler2.scala
- src/main/scala/pdf2excel/data.scala
- src/main/scala/pdf2excel/ing/IngPageHandler.scala
- src/main/scala/pdf2excel/nab/NabPageHandler.scala
Fix the improperly handled pattern matching
> Fix the improperly handled pattern matching

- project/plugins.sbt
- src/main/scala/kevinlee/parsers/Parsers.scala
Bump sbt plugins
- sbt-wartremover to 3.1.6
- sbt-devoops to 3.0.0
> Bump sbt plugins

- .github/workflows/build.yml
- .github/workflows/sbt-build-all.sh
Add GitHub Actions build - `build.yml`
> Add GitHub Actions build - `build.yml`

- project/plugins.sbt
Bump sbt-wartremover to 3.2.2 / sbt-devoops to 3.1.0
> Bump sbt-wartremover to 3.2.2 / sbt-devoops to 3.1.0

- .github/pr-labeler.yml
- .github/workflows/pr-labeler.yml
GitHub Actions: Add PR Labeler
> GitHub Actions: Add PR Labeler

- build.sbt
- src/main/scala-2/pdf2excel/Args.scala
- src/main/scala-3/pdf2excel/Args.scala
- src/main/scala/pdf2excel/Pdf2Excel.scala
- src/main/scala/pdf2excel/Pdf2ExcelApp.scala
- src/main/scala/pdf2excel/cba/CbaPageHandler.scala
- src/main/scala/pdf2excel/cba/CbaPageHandler2.scala
- src/main/scala/pdf2excel/data.scala
- src/main/scala/pdf2excel/nab/NabPageHandler.scala
Close #49 - Add the statement type parameter to get the PDF page handler for the bank statement
> Close #49 - Add the statement type parameter to get the PDF page handler for the bank statement

- project/build.properties
> Bump sbt to 1.10.3

- src/main/scala/pdf2excel/Pdf2Excel.scala
- src/main/scala/pdf2excel/Pdf2ExcelApp.scala
- src/main/scala/pdf2excel/cba/CbaPageHandler.scala
- src/main/scala/pdf2excel/cba/CbaPageHandler2.scala
- src/main/scala/pdf2excel/data.scala
- src/main/scala/pdf2excel/ing/IngPageHandler.scala
- src/main/scala/pdf2excel/nab/NabPageHandler.scala
Refactor: Make `postProcess` optional. `def postProcess(a: A): A` => `def getPostProcess: Option[A => A]`
> Refactor: Make `postProcess` optional. `def postProcess(a: A): A` => `def getPostProcess: Option[A => A]`

- src/main/scala-2/pdf2excel/Args.scala
- src/main/scala-3/pdf2excel/Args.scala
- src/main/scala/pdf2excel/Pdf2Excel.scala
- src/main/scala/pdf2excel/latitude/Latitude28DegreeGlobalPageHandler.scala
Close #55 - Add Latitude 28° Global Platinum Card transaction statement handler
> Close #55 - Add Latitude 28° Global Platinum Card transaction statement handler

- .github/pr-labeler.yml
Fix `pr-labeler.yml` - remove v2 label
> Fix `pr-labeler.yml` - remove v2 label

- project/build.properties
> Bump sbt to 1.10.6

- build.sbt
> Bump Scala version to 3.3.5

- project/plugins.sbt
Bump sbt-wartremover plugin to version 3.3.0
> Bump sbt-wartremover plugin to version 3.3.0

- .github/workflows/build.yml
Update build configuration: switch to `actions/setup-java` and simplify caching
> Update build configuration: switch to `actions/setup-java` and simplify caching
